name: Run The Build Script™

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checksum the files
        run: find src -type f -exec md5sum {} \;
      - name: Output the manifest.json file
        run: cat src/manifest.json
      - name: Run the Build Script
        run: auto/build
      - name: Get a checksum for the zip file
        run: md5sum build/*.zip
