name: Build

on:
  push:
    branches-ignore: [main]

jobs:
  build_zip:
    name: "Build - zip package"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: Run build script
        run: auto/build

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: chrome-package
          path: build/aws-rolex.zip

  build_web-ext:
    name: "Build - web-ext package"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: src

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: mozilla-package
          path: ${{ steps.web-ext-build.outputs.target }}

  build_safari:
    name: "Build - Safari Extension Converter"
    runs-on: macos-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "Running: safari-web-extension-converter"
        run: xcrun /Applications/Xcode.app/Contents/Developer/usr/bin/safari-web-extension-converter --no-open --no-prompt --copy-resources ./src/

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: apple-extension
          path: "./AWS RolEx/"
