name: Build and Publish

on:
  push:
    branches: main

jobs:
  build_zip:
    name: "Build - zip package"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: Run build script
        run: auto/build

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: chrome-package
          path: build/aws-rolex.zip

  build_web-ext:
    name: "Build - web-ext package"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: src

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: firefox-package
          path: ${{ steps.web-ext-build.outputs.target }}
