name: Build and publish to the Firefox Addons marketplace

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: src

      - name: "web-ext sign"
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: ${{ steps.web-ext-build.outputs.target }}
          channel: listed
          apiKey: ${{ secrets.AMO_SIGN_KEY }}
          apiSecret: ${{ secrets.AMO_SIGN_SECRET }}
          timeout: 900000

      - uses: trmcnvn/firefox-addon@v1
        with:
          uuid: '{75a0b0c5-4107-4731-a745-aa3d305a3934}'
          xpi: ${{ steps.web-ext-build.outputs.target }}
          manifest: src/manifest.json
          api-key: ${{ secrets.FIREFOX_JWT_ISSUER }}
          api-secret: ${{ secrets.FIREFOX_JWT_SECRET }}

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: target.xpi
          path: ${{ steps.web-ext-build.outputs.target }}
