# Creates a GitHub release
on:
  push:
    tags: ["v*"]

name: Create Release

jobs:
  lint:
    name: "web-ext lint"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: web-ext install
        run: npm install --global web-ext

      - name: web-ext lint
        run: cd src && web-ext lint

  build_zip:
    name: "Build - Zip Package"
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: Run build script
        run: auto/build

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: zip-package
          path: build/aws-rolex.zip

  # Thanks, Google.
  build_chrome:
    name: "Build - Chrome Package"
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: Remove unsupported keys
        run: jq '. | del(.browser_specific_settings)' src/manifest.json > manifest.json.new && mv -v manifest.json.new src/manifest.json

      - name: Run build script
        run: auto/build

      - name: Rename file
        run: mv -v build/aws-rolex.zip build/aws-rolex-chrome.zip

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: chrome-package
          path: build/aws-rolex-chrome.zip

  build_firefox:
    name: "Build - Firefox Package"
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: web-ext build
        run: npx web-ext build --source-dir ./src/ --artifacts-dir ./build/ --filename "aws-rolex-firefox.xpi"

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: firefox-package
          path: build/*.xpi

  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs:
      - build_zip
      - build_chrome
      - build_firefox
    permissions:
      contents: write
    steps:
      
      - name: Download zip-package
        uses: actions/download-artifact@v4
        with:
          name: zip-package
          path: build/

      - name: Download chrome-package
        uses: actions/download-artifact@v4
        with:
          name: chrome-package
          path: build/

      - name: Download firefox-package
        uses: actions/download-artifact@v4
        with:
          name: firefox-package
          path: build/

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            build/*.zip
            build/*.xpi
          body: |
            Release: Version ${{ github.ref_name }}
